"use client";

import { useI18n } from "@/lib/i18n";

export const adminCopy = {
  vi: {
    common: {
      activity: "Lịch sử hoạt động",
      overview: "Tổng quan", users: "Người dùng", exercises: "Bài tập", adminManagement: "Quản lý admin", account: "Tài khoản",
      navigation: "Điều hướng", changePassword: "Đổi mật khẩu", signOut: "Đăng xuất",
      loadingAuth: "Đang xác thực...", deniedTitle: "Không có quyền truy cập",
      deniedBody: "Khu vực này chỉ dành cho tài khoản admin.", backToStudent: "Về trang người học",
      changeRequired: "Vui lòng đổi mật khẩu trước khi tiếp tục.", openMenu: "Mở menu", closeMenu: "Đóng menu",
      accountMenu: "Menu tài khoản",
      all: "Tất cả", active: "Đang bật", inactive: "Vô hiệu hóa", previous: "Trước", next: "Sau",
      view: "Xem", viewAll: "Xem tất cả", details: "Chi tiết", edit: "Biên tập", joined: "Tham gia",
      status: "Trạng thái", updated: "Cập nhật", noResults: "Không có kết quả",
      draft: "Bản nháp", review: "Chờ duyệt", approved: "Đã duyệt", published: "Đã xuất bản",
      page: "Trang", results: "kết quả",
    },
    overview: {
      eyebrow: "Quản trị hệ thống", title: "Tổng quan", description: "Theo dõi người học, bài tập và nội dung đang chờ xử lý trong một nơi.",
      users: "Người dùng", activeUsers: "tài khoản đang bật", exercises: "Bài tập", published: "đã xuất bản",
      attempts: "Lượt làm bài", attemptDetail: "Từ các tài khoản người học", pending: "Chờ duyệt", pendingDetail: "Cần xem nội dung",
      pendingTitle: "Bài tập chờ duyệt", pendingDescription: "Kiểm tra nội dung trước khi xuất bản",
      recentUsers: "Người dùng gần đây", recentDescription: "Sắp theo ngày tham gia", updated: "cập nhật",
      noRecent: "Chưa có người dùng.", noPending: "Không có bài tập chờ duyệt.",
      workflow: "Quy trình quản lý bài tập", workflowBody: "Lưu nháp → kiểm tra → admin khác duyệt → xuất bản. Mọi thao tác được ghi vào nhật ký quản trị.",
      openExercises: "Mở thư viện bài tập →",
    },
    users: {
      eyebrow: "Tài khoản", title: "Người dùng", description: "Tra cứu tài khoản và tiến độ học tập từ dữ liệu hệ thống.",
      search: "Tìm kiếm", searchPlaceholder: "Tên, email hoặc ID", status: "Trạng thái",
      user: "Người dùng", completed: "Hoàn thành", averageScore: "Điểm TB", empty: "Không tìm thấy người dùng",
      emptyHelp: "Thử từ khóa hoặc bộ lọc khác.", loadError: "Không thể tải danh sách người dùng", restricted: "Chức năng khóa, xóa hoặc đổi role sẽ cần API và chính sách phân quyền riêng.",
    },
    detail: {
      back: "Danh sách người dùng", account: "Tài khoản", description: "Thông tin tài khoản và tiến độ làm bài từ dữ liệu hệ thống.",
      notFound: "Không tìm thấy người dùng", loadError: "Không thể tải thông tin người dùng",
      joined: "Ngày tham gia", lastActive: "Lần làm bài gần nhất", progress: "Tiến độ học tập",
      progressDescription: "Tóm tắt từ các lượt làm bài đã lưu.", attempts: "Lượt làm bài", completed: "Đã hoàn thành",
      averageScore: "Điểm trung bình", completion: "Hoàn thành",
    },
    exercises: {
      eyebrow: "Nội dung học tập", title: "Bài tập", description: "Theo dõi trạng thái nội dung, xem test case và chuẩn bị bản sửa cho quy trình duyệt.",
      search: "Tìm bài tập", searchPlaceholder: "Mã hoặc tiêu đề", status: "Trạng thái", level: "Cấp độ", kind: "Loại bài",
      exercise: "Bài tập", updated: "Cập nhật", details: "Chi tiết", empty: "Không tìm thấy bài tập",
      emptyHelp: "Thử thay đổi bộ lọc hoặc từ khóa.",
    },
    editor: {
      back: "Danh sách bài tập", notFound: "Không tìm thấy bài tập", notFoundBody: "không có trong hệ thống.",
      description: "Biên tập và lưu bản nháp vào hệ thống trước khi gửi duyệt.",
      process: "QUY TRÌNH", draft: "Bản nháp", check: "Kiểm tra", approve: "Duyệt", publish: "Xuất bản",
      sampleUpdated: "Đã cập nhật", unsaved: "Có thay đổi chưa lưu. Hãy lưu bản nháp trước khi rời trang.",
      restore: "Khôi phục bản gốc", restoreConfirm: "Bỏ tất cả thay đổi chưa tải xuống?",
      basics: "Thông tin cơ bản", basicsHelp: "Các thay đổi thông tin được lưu cùng bản nháp bài tập.",
      code: "Mã bài tập", title: "Tiêu đề", level: "Cấp độ", kindDifficulty: "Loại · độ khó",
      content: "Đề bài và code", summary: "Nội dung đề bài", starter: "Code khởi tạo", hint: "Gợi ý",
      reference: "Lời giải tham chiếu · chỉ dành cho admin", tests: "Test cases",
      testsHelp: "Test ẩn không được đưa vào API người học.", addTest: "Thêm test", removeTest: "Xóa test",
      descriptionLabel: "Mô tả", input: "Input", expected: "Kết quả mong đợi", category: "Nhóm", hidden: "Test ẩn",
      mutants: "Mutants", mutantsHelp: "Các lời giải sai có chủ đích để kiểm tra chất lượng test.",
      addMutant: "Thêm mutant", removeMutant: "Xóa mutant", bugLine: "Dòng lỗi", bugType: "Loại lỗi",
      noteVi: "Giải thích tiếng Việt", noteEn: "Giải thích tiếng Anh", skillsReview: "Kỹ năng và review",
      skills: "Skill tags · ngăn cách bằng dấu phẩy", reviewDraft: "Bản nháp chưa được duyệt",
      reviewHelp: "Backend kiểm tra và lưu các bước duyệt, từ chối và xuất bản.",
      sections: "Mục nội dung", basicCheck: "Kiểm tra cơ bản", download: "Tải bản nháp JSON",
      notSaved: "Lưu bản nháp và kiểm tra trên backend trước khi gửi duyệt.",
      needsFix: "Cần bổ sung", items: "mục", passed: "Đạt kiểm tra cơ bản",
      passedHelp: "Cần chạy validator đầy đủ trên backend trước khi duyệt.", downloaded: "Đã tải bản nháp JSON xuống thiết bị.",
      invalidCode: "Mã bài tập cần có dạng CP-001.", missingSummary: "Cần nhập nội dung đề bài.",
      missingReference: "Cần nhập lời giải tham chiếu.", missingStarter: "Cần nhập code khởi tạo.",
      missingTest: "Cần ít nhất một test case.", invalidTest: "Mỗi test case cần mô tả và input.",
      invalidMutant: "Mỗi mutant cần code, dòng lỗi và loại lỗi.",
    },
    login: {
      title: "Đăng nhập quản trị", description: "Sử dụng email và mật khẩu riêng được cấp cho bạn.",
      firstLogin: "Lần đăng nhập đầu tiên sẽ yêu cầu đổi mật khẩu.", password: "Mật khẩu",
      missing: "Nhập email và mật khẩu được cấp.", failed: "Đăng nhập thất bại.",
      show: "Hiện mật khẩu", hide: "Ẩn mật khẩu", signingIn: "Đang đăng nhập...", signIn: "Đăng nhập",
      noGoogle: "Không có đăng ký hoặc Google OAuth cho admin.", backHome: "Về trang chủ",
    },
    password: {
      eyebrow: "Bảo mật tài khoản", title: "Đổi mật khẩu", description: "Mỗi admin sử dụng tài khoản riêng. Hãy đổi mật khẩu được cấp trong lần đăng nhập đầu tiên.",
      privacy: "Mật khẩu chỉ được gửi tới API khi bạn xác nhận. Giao diện không lưu mật khẩu trong localStorage hoặc dữ liệu mẫu.",
      section: "Thông tin mật khẩu", sectionHelp: "Dùng mật khẩu mạnh và không chia sẻ với tài khoản khác.",
      current: "Mật khẩu hiện tại", next: "Mật khẩu mới", confirm: "Xác nhận mật khẩu mới",
      hint: "Từ 15 ký tự, tối đa 72 byte UTF-8, khác mật khẩu hiện tại.", show: "Hiện mật khẩu", hide: "Ẩn mật khẩu",
      missingCurrent: "Nhập mật khẩu hiện tại.", tooShort: "Mật khẩu mới cần ít nhất 15 ký tự.", tooLong: "Mật khẩu mới quá dài (tối đa 72 byte UTF-8).",
      same: "Mật khẩu mới phải khác mật khẩu hiện tại.", mismatch: "Mật khẩu xác nhận chưa khớp.",
      expired: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.", unavailable: "Backend chưa hỗ trợ đổi mật khẩu admin.",
      failed: "Không thể đổi mật khẩu. Vui lòng thử lại.", connection: "Không thể kết nối máy chủ.",
      needsApi: "Mật khẩu mới chỉ mình bạn biết.", updating: "Đang cập nhật...", update: "Cập nhật mật khẩu",
    },
    notFound: { code: "404", title: "Không tìm thấy trang", body: "Đường dẫn quản trị này không tồn tại hoặc đã thay đổi.", back: "Về tổng quan" },
    loading: "Đang tải trang quản trị",
  },
  en: {
    common: {
      activity: "Activity history",
      overview: "Overview", users: "Users", exercises: "Exercises", adminManagement: "Manage admins", account: "Account",
      navigation: "Navigation", changePassword: "Change password", signOut: "Sign out",
      loadingAuth: "Checking your account...", deniedTitle: "Access denied",
      deniedBody: "This area is for admin accounts only.", backToStudent: "Back to learner area",
      changeRequired: "Please change your password before continuing.", openMenu: "Open menu", closeMenu: "Close menu",
      accountMenu: "Account menu",
      all: "All", active: "Enabled", inactive: "Disabled", previous: "Previous", next: "Next",
      view: "View", viewAll: "View all", details: "Details", edit: "Edit", joined: "Joined",
      status: "Status", updated: "Updated", noResults: "No results",
      draft: "Draft", review: "In review", approved: "Approved", published: "Published",
      page: "Page", results: "results",
    },
    overview: {
      eyebrow: "System administration", title: "Overview", description: "Track learners, exercises and content awaiting review in one place.",
      users: "Users", activeUsers: "enabled accounts", exercises: "Exercises", published: "published",
      attempts: "Attempts", attemptDetail: "From learner accounts", pending: "In review", pendingDetail: "Needs review",
      pendingTitle: "Exercises in review", pendingDescription: "Check content before publishing",
      recentUsers: "Recent users", recentDescription: "Sorted by join date", updated: "updated",
      noRecent: "No users yet.", noPending: "No exercises awaiting review.",
      workflow: "Exercise workflow", workflowBody: "Save draft → validate → another admin reviews → publish. Each action is recorded in the admin audit log.",
      openExercises: "Open exercise library →",
    },
    users: {
      eyebrow: "Accounts", title: "Users", description: "Look up accounts and learning progress from system data.",
      search: "Search", searchPlaceholder: "Name, email or ID", status: "Status",
      user: "User", completed: "Completed", averageScore: "Avg. score", empty: "No users found",
      emptyHelp: "Try another search or filter.", loadError: "Could not load users", restricted: "Suspending, deleting or changing roles requires separate APIs and authorization rules.",
    },
    detail: {
      back: "User list", account: "Account", description: "Account and attempt progress from system data.",
      notFound: "User not found", loadError: "Could not load user details",
      joined: "Join date", lastActive: "Last attempt", progress: "Learning progress",
      progressDescription: "Summary from saved attempts.", attempts: "Attempts", completed: "Completed",
      averageScore: "Average score", completion: "Completion",
    },
    exercises: {
      eyebrow: "Learning content", title: "Exercises", description: "Track content status, inspect test cases and prepare changes for review.",
      search: "Search exercises", searchPlaceholder: "Code or title", status: "Status", level: "Level", kind: "Type",
      exercise: "Exercise", updated: "Updated", details: "Details", empty: "No exercises found",
      emptyHelp: "Try another search or filter.",
    },
    editor: {
      back: "Exercise list", notFound: "Exercise not found", notFoundBody: "is not in the system.",
      description: "Edit and save a content draft before submitting it for review.",
      process: "WORKFLOW", draft: "Draft", check: "Validate", approve: "Review", publish: "Publish",
      sampleUpdated: "Updated", unsaved: "You have unsaved changes. Save the draft before leaving this page.",
      restore: "Restore original", restoreConfirm: "Discard all changes that have not been downloaded?",
      basics: "Basic information", basicsHelp: "Metadata changes are saved with the exercise draft.",
      code: "Exercise code", title: "Title", level: "Level", kindDifficulty: "Type · difficulty",
      content: "Prompt and code", summary: "Problem statement", starter: "Starter code", hint: "Hint",
      reference: "Reference solution · admins only", tests: "Test cases",
      testsHelp: "Hidden tests must not be exposed through learner APIs.", addTest: "Add test", removeTest: "Remove test",
      descriptionLabel: "Description", input: "Input", expected: "Expected result", category: "Category", hidden: "Hidden test",
      mutants: "Mutants", mutantsHelp: "Intentionally incorrect solutions used to assess test quality.",
      addMutant: "Add mutant", removeMutant: "Remove mutant", bugLine: "Bug line", bugType: "Bug type",
      noteVi: "Vietnamese explanation", noteEn: "English explanation", skillsReview: "Skills and review",
      skills: "Skill tags · comma separated", reviewDraft: "Draft has not been approved",
      reviewHelp: "The backend validates and stores review, rejection and publication steps.",
      sections: "Sections", basicCheck: "Basic check", download: "Download draft JSON",
      notSaved: "Save and validate the draft on the backend before submitting it for review.",
      needsFix: "Fix", items: "items", passed: "Basic check passed",
      passedHelp: "Run the full backend validator before approval.", downloaded: "Draft JSON downloaded to your device.",
      invalidCode: "Exercise code must look like CP-001.", missingSummary: "Enter a problem statement.",
      missingReference: "Enter a reference solution.", missingStarter: "Enter starter code.",
      missingTest: "Add at least one test case.", invalidTest: "Every test case needs a description and input.",
      invalidMutant: "Every mutant needs code, a bug line and a bug type.",
    },
    login: {
      title: "Admin sign in", description: "Use the email and password assigned to your account.",
      firstLogin: "You will be asked to change your password on your first sign in.", password: "Password",
      missing: "Enter your assigned email and password.", failed: "Sign in failed.",
      show: "Show password", hide: "Hide password", signingIn: "Signing in...", signIn: "Sign in",
      noGoogle: "Admin accounts do not use public signup or Google OAuth.", backHome: "Back to home",
    },
    password: {
      eyebrow: "Account security", title: "Change password", description: "Each admin has a separate account. Change your assigned password on your first sign in.",
      privacy: "Your password is sent to the API only when you submit. The UI does not store it in localStorage or sample data.",
      section: "Password details", sectionHelp: "Use a strong password and do not share it with another account.",
      current: "Current password", next: "New password", confirm: "Confirm new password",
      hint: "At least 15 characters, at most 72 UTF-8 bytes, different from your current password.", show: "Show password", hide: "Hide password",
      missingCurrent: "Enter your current password.", tooShort: "The new password must have at least 15 characters.", tooLong: "The new password is too long (maximum 72 UTF-8 bytes).",
      same: "The new password must differ from the current password.", mismatch: "The confirmation does not match.",
      expired: "Your session expired. Please sign in again.", unavailable: "The backend does not support admin password changes yet.",
      failed: "Could not change your password. Please try again.", connection: "Could not connect to the server.",
      needsApi: "Only you know your new password.", updating: "Updating...", update: "Update password",
    },
    notFound: { code: "404", title: "Page not found", body: "This admin URL does not exist or has changed.", back: "Back to overview" },
    loading: "Loading admin page",
  },
} as const;

export function useAdminCopy() {
  const { locale } = useI18n();
  return { locale, t: adminCopy[locale] };
}
