"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, Check, Download, Plus, Trash2 } from "lucide-react";
import { exercises, formatDate, statusLabel, statusTone, type AdminExercise, type AdminMutant, type AdminTest } from "../../_data";
import { BackLink, card, field, PageHeading, PreviewNotice, primaryButton, secondaryButton } from "../../_ui";

const inputLabel = "mb-1.5 block text-xs font-semibold text-on-surface-variant";
const monoField = `${field} font-[ui-monospace,SFMono-Regular,Consolas,monospace] leading-relaxed`;

function validateDraft(exercise: AdminExercise): string[] {
  const issues: string[] = [];
  if (!/^CP-\d{3}$/.test(exercise.code)) issues.push("Mã bài tập cần có dạng CP-001.");
  if (!exercise.summary.trim()) issues.push("Cần nhập nội dung đề bài.");
  if (!exercise.referenceSolution.trim()) issues.push("Cần nhập lời giải tham chiếu.");
  if (!exercise.starterCode.trim()) issues.push("Cần nhập code khởi tạo.");
  if (exercise.tests.length < 1) issues.push("Cần ít nhất một test case.");
  if (exercise.tests.some((test) => !test.description.trim() || !test.input.trim())) issues.push("Mỗi test case cần mô tả và input.");
  if (exercise.mutants.some((mutant) => !mutant.code.trim() || mutant.bugLine < 1 || !mutant.bugType.trim())) issues.push("Mỗi mutant cần code, dòng lỗi và loại lỗi.");
  return issues;
}

function downloadDraft(exercise: AdminExercise) {
  // This matches the content-file shape. It is a draft for code review, not a publish action.
  const payload = {
    code: exercise.code,
    reference_solution: exercise.referenceSolution.split("\n"),
    tests: exercise.tests,
    mutants: exercise.mutants.map((item) => ({ code: item.code.split("\n"), bug_line: item.bugLine, bug_type: item.bugType, note_vi: item.noteVi, note_en: item.noteEn })),
    exercise: { summary: exercise.summary, starter_code: exercise.starterCode.split("\n"), hint: exercise.hint },
    skills: exercise.skills.length ? { tags: exercise.skills, review: { status: "draft", author: "admin-ui", reviewer: null } } : undefined,
    review: { status: "draft", author: "admin-ui", reviewer: null },
  };
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${exercise.code}-draft.json`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export default function AdminExerciseEditorPage({ params }: { params: { code: string } }) {
  const source = useMemo(() => exercises.find((item) => item.code === params.code), [params.code]);
  const [draft, setDraft] = useState<AdminExercise | null>(() => source ? structuredClone(source) : null);
  const [checked, setChecked] = useState(false);
  const [exported, setExported] = useState(false);
  if (!source || !draft) return <div><BackLink href="/admin/exercises?demo=1">Danh sách bài tập</BackLink><h1 className="text-2xl font-bold">Không tìm thấy bài tập</h1><p className="mt-2 text-on-surface-variant">Mã {params.code} không có trong dữ liệu minh họa.</p></div>;

  const issues = validateDraft(draft);
  const isDirty = JSON.stringify(draft) !== JSON.stringify(source);
  const setValue = <K extends keyof AdminExercise>(key: K, value: AdminExercise[K]) => { setDraft((current) => current ? { ...current, [key]: value } : current); setChecked(false); setExported(false); };
  const updateTest = (index: number, patch: Partial<AdminTest>) => setValue("tests", draft.tests.map((item, position) => position === index ? { ...item, ...patch } : item));
  const updateMutant = (index: number, patch: Partial<AdminMutant>) => setValue("mutants", draft.mutants.map((item, position) => position === index ? { ...item, ...patch } : item));

  return <div className="pb-12"><BackLink href="/admin/exercises?demo=1">Danh sách bài tập</BackLink><PageHeading eyebrow={`${draft.code} · ${draft.level}`} title={draft.title} description="Biên tập bản nháp nội dung. Thay đổi chỉ nằm trong phiên trình duyệt cho tới khi bạn tải JSON về." action={<span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${statusTone[source.status]}`}>{statusLabel[source.status]}</span>} /><PreviewNotice />
    <div className="mb-6 flex flex-wrap items-center gap-2 rounded-xl border border-outline-variant/60 bg-surface-container-low p-4 text-xs"><span className="font-semibold text-on-surface-variant">QUY TRÌNH</span>{["Bản nháp", "Kiểm tra", "Duyệt", "Xuất bản"].map((step, index) => <span key={step} className={`rounded-lg px-3 py-1.5 ${index === 0 ? "bg-primary/15 font-semibold text-primary" : "bg-surface-container-high text-on-surface-variant"}`}>{index + 1}. {step}</span>)}<span className="ml-auto text-on-surface-variant">Cập nhật mẫu: {formatDate(source.updatedAt)}</span></div>
    {isDirty && <div role="status" className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/30 bg-primary/10 px-4 py-3 text-sm"><span>Đang có thay đổi trong phiên này. Hãy tải JSON trước khi rời trang.</span><button type="button" onClick={() => { if (window.confirm("Bỏ tất cả thay đổi chưa tải xuống?")) { setDraft(structuredClone(source)); setChecked(false); setExported(false); } }} className="font-semibold text-primary hover:underline">Khôi phục bản gốc</button></div>}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_260px]"><div className="space-y-6">
      <section id="basics" className={`${card} p-5 sm:p-6`}><h2 className="text-lg font-bold">Thông tin cơ bản</h2><p className="mt-1 text-sm text-on-surface-variant">Mã, tiêu đề, cấp độ và loại bài lấy từ bản ghi gốc; API quản lý metadata chưa có.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><span className={inputLabel}>Mã bài tập</span><p className={`${field} flex items-center opacity-70`}>{draft.code}</p></div><div><span className={inputLabel}>Tiêu đề</span><p className={`${field} flex items-center opacity-70`}>{draft.title}</p></div><div><span className={inputLabel}>Cấp độ</span><p className={`${field} flex items-center capitalize opacity-70`}>{draft.level}</p></div><div><span className={inputLabel}>Loại · độ khó</span><p className={`${field} flex items-center capitalize opacity-70`}>{draft.kind} · {draft.difficulty}</p></div></div></section>
      <section id="content" className={`${card} p-5 sm:p-6`}><h2 className="text-lg font-bold">Đề bài và code</h2><div className="mt-5 space-y-4"><label className="block"><span className={inputLabel}>Nội dung đề bài</span><textarea rows={5} value={draft.summary} onChange={(event) => setValue("summary", event.target.value)} className={field} /></label><label className="block"><span className={inputLabel}>Code khởi tạo</span><textarea rows={7} value={draft.starterCode} onChange={(event) => setValue("starterCode", event.target.value)} spellCheck={false} className={monoField} /></label><label className="block"><span className={inputLabel}>Gợi ý</span><textarea rows={3} value={draft.hint} onChange={(event) => setValue("hint", event.target.value)} className={field} /></label><label className="block"><span className={inputLabel}>Lời giải tham chiếu · chỉ dành cho admin</span><textarea rows={8} value={draft.referenceSolution} onChange={(event) => setValue("referenceSolution", event.target.value)} spellCheck={false} className={monoField} /></label></div></section>
      <section id="tests" className={`${card} p-5 sm:p-6`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Test cases</h2><p className="mt-1 text-sm text-on-surface-variant">Test ẩn không được đưa vào API người học.</p></div><button type="button" onClick={() => setValue("tests", [...draft.tests, { description: "", input: "", expected: "", category: "happy", hidden: true }])} className={secondaryButton}><Plus size={16} /> Thêm test</button></div><div className="mt-5 space-y-4">{draft.tests.map((test, index) => <div key={index} className="rounded-xl border border-outline-variant/60 bg-surface-container-low p-4"><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-semibold">Test #{index + 1}</h3><button type="button" aria-label={`Xóa test ${index + 1}`} onClick={() => setValue("tests", draft.tests.filter((_, position) => position !== index))} className="rounded-lg p-2 text-error hover:bg-error/10"><Trash2 size={16} /></button></div><div className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className={inputLabel}>Mô tả</span><input value={test.description} onChange={(event) => updateTest(index, { description: event.target.value })} className={field} /></label><label><span className={inputLabel}>Input</span><input value={test.input} onChange={(event) => updateTest(index, { input: event.target.value })} className={monoField} /></label><label><span className={inputLabel}>Kết quả mong đợi</span><input value={test.expected} onChange={(event) => updateTest(index, { expected: event.target.value })} className={monoField} /></label><label><span className={inputLabel}>Nhóm</span><select value={test.category} onChange={(event) => updateTest(index, { category: event.target.value as AdminTest["category"] })} className={field}><option value="happy">Happy</option><option value="boundary">Boundary</option><option value="edge">Edge</option><option value="error">Error</option></select></label><label className="flex items-center gap-2 self-end pb-2 text-sm"><input type="checkbox" checked={test.hidden} onChange={(event) => updateTest(index, { hidden: event.target.checked })} className="accent-primary" /> Test ẩn</label></div></div>)}</div></section>
      <section id="mutants" className={`${card} p-5 sm:p-6`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Mutants</h2><p className="mt-1 text-sm text-on-surface-variant">Các lời giải sai có chủ đích để kiểm tra chất lượng test.</p></div><button type="button" onClick={() => setValue("mutants", [...draft.mutants, { code: "", bugLine: 1, bugType: "", noteVi: "", noteEn: "" }])} className={secondaryButton}><Plus size={16} /> Thêm mutant</button></div><div className="mt-5 space-y-4">{draft.mutants.map((mutant, index) => <div key={index} className="rounded-xl border border-outline-variant/60 bg-surface-container-low p-4"><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-semibold">Mutant #{index + 1}</h3><button type="button" aria-label={`Xóa mutant ${index + 1}`} onClick={() => setValue("mutants", draft.mutants.filter((_, position) => position !== index))} className="rounded-lg p-2 text-error hover:bg-error/10"><Trash2 size={16} /></button></div><div className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className={inputLabel}>Code</span><textarea rows={5} value={mutant.code} onChange={(event) => updateMutant(index, { code: event.target.value })} spellCheck={false} className={monoField} /></label><label><span className={inputLabel}>Dòng lỗi</span><input type="number" min={1} value={mutant.bugLine} onChange={(event) => updateMutant(index, { bugLine: Number(event.target.value) })} className={field} /></label><label><span className={inputLabel}>Loại lỗi</span><input value={mutant.bugType} onChange={(event) => updateMutant(index, { bugType: event.target.value })} className={field} /></label><label><span className={inputLabel}>Giải thích tiếng Việt</span><input value={mutant.noteVi} onChange={(event) => updateMutant(index, { noteVi: event.target.value })} className={field} /></label><label><span className={inputLabel}>Explanation in English</span><input value={mutant.noteEn} onChange={(event) => updateMutant(index, { noteEn: event.target.value })} className={field} /></label></div></div>)}</div></section>
      <section id="review" className={`${card} p-5 sm:p-6`}><h2 className="text-lg font-bold">Kỹ năng và review</h2><label className="mt-5 block"><span className={inputLabel}>Skill tags · ngăn cách bằng dấu phẩy</span><input value={draft.skills.join(", ")} onChange={(event) => setValue("skills", event.target.value.split(",").map((item) => item.trim()).filter(Boolean))} className={field} /></label><div className="mt-5 rounded-xl border border-warning/40 bg-warning/10 p-4 text-sm text-on-surface"><p className="font-semibold">Bản nháp chưa được duyệt</p><p className="mt-1 text-on-surface-variant">File xuất từ UI luôn có review.status = draft. Quy trình validate, reviewer và sync vẫn thực hiện ở backend.</p></div></section>
    </div><aside className="xl:sticky xl:top-24 xl:self-start"><div className={`${card} p-5`}><h2 className="font-bold">Mục nội dung</h2><nav aria-label="Mục biên tập" className="mt-4 space-y-2 text-sm text-on-surface-variant">{[["basics", "Thông tin cơ bản"], ["content", "Đề bài và code"], ["tests", `Test cases (${draft.tests.length})`], ["mutants", `Mutants (${draft.mutants.length})`], ["review", "Kỹ năng và review"]].map(([id, label]) => <a key={id} href={`#${id}`} className="block rounded-lg px-2 py-1.5 hover:bg-surface-container hover:text-primary">{label}</a>)}</nav><div className="mt-5 border-t border-outline-variant/50 pt-5"><button type="button" onClick={() => setChecked(true)} className={`${secondaryButton} w-full`}><Check size={16} />Kiểm tra cơ bản</button><button type="button" onClick={() => { downloadDraft(draft); setExported(true); }} className={`${primaryButton} mt-2 w-full`}><Download size={16} />Tải bản nháp JSON</button><p className="mt-3 text-xs text-on-surface-variant">Không lưu vào hệ thống. Kiểm tra backend vẫn cần chạy trước khi duyệt.</p></div></div>{checked && <div role="status" className={`${card} mt-4 p-4 text-sm`}>{issues.length ? <><p className="flex items-center gap-2 font-semibold text-warning"><AlertTriangle size={17} />Cần bổ sung {issues.length} mục</p><ul className="mt-2 list-inside list-disc space-y-1 text-on-surface-variant">{issues.map((issue) => <li key={issue}>{issue}</li>)}</ul></> : <><p className="flex items-center gap-2 font-semibold text-primary"><Check size={17} />Đạt kiểm tra cơ bản</p><p className="mt-1 text-on-surface-variant">Cần chạy validator đầy đủ trên backend trước khi duyệt.</p></>}</div>}{exported && <p role="status" className="mt-3 text-sm text-primary">Đã tải bản nháp JSON xuống thiết bị.</p>}</aside></div>
  </div>;
}
