// Bilingual UI strings for the authenticated app surfaces (dashboard, workspace,
// exercise list, solve screen). Kept separate from the large marketing dictionary
// in content.ts. Consume via: const { locale } = useI18n(); const t = appContent[locale];

export const appContent = {
  vi: {
    nav: { dashboard: "Bảng điều khiển", progress: "Tiến độ", workspace: "Phòng luyện", analytics: "Phân tích", daily: "Bug Hunt", problems: "Bài tập", leaderboard: "Xếp hạng", practice: "Visualizer", community: "Cộng đồng" },
    dashboard: {
      eyebrow: "Tổng quan hệ thống",
      dailyTitle: "Bug Hunt hôm nay",
      dailyBody: "Ciel đã cài 1 lỗi tinh vi vào đoạn code hôm nay. Bắt được trong 60 giây để đạt hạng xanh và giữ chuỗi ngày của bạn.",
      dailyCta: "Chơi ngay",
      recommendedTitle: "Bài nên làm tiếp",
      recommendedPractise: "Luyện",
      recommendedDebug: "Debug",
      welcome: "Chào mừng trở lại",
      loadingSub: "Đang tải tiến trình của bạn...",
      emptySub: "Bắt đầu thử thách đầu tiên để xem tiến trình tại đây.",
      readySub: "Bảng năng lực AI hiển thị dữ liệu tổng hợp thật từ các lần làm đã chấm.",
      loading: "Đang tải bảng điều khiển…",
      loadFailed: "Tải bảng điều khiển thất bại",
      emptyTitle: "Chưa có lần làm nào - bắt đầu một thử thách",
      emptyDesc: "Hoàn thành một bài đã chấm điểm để xem chỉ số năng lực tại đây.",
      goWorkspace: "Tới phòng luyện",
      kpiCompleted: "Bài đã hoàn thành",
      kpiCompletedDelta: "bài đã chấm",
      kpiStreak: "Chuỗi ngày",
      kpiStreakDelta: "ngày hoạt động",
      kpiAvg: "Điểm năng lực TB",
      kpiAvgDelta: "trên thang 100",
      matrixTitle: "Ma trận năng lực",
      matrixSub: "Hồ sơ năng lực AI 6 trục",
      recentTitle: "Lần làm gần đây",
      recentLast: "6 GẦN NHẤT",
      viewAll: "Xem tất cả hoạt động",
      trendTitle: "Xu hướng năng lực",
      trendSub: "Điểm qua các lần làm gần đây",
      byAxisTitle: "Hiệu suất theo trục",
      pts: "điểm",
    },
    progress: {
      eyebrow: "Mô hình học viên",
      title: "Tiến độ",
      sub: "Bạn mạnh ở đâu, cần luyện gì, và các trục đang đi lên hay xuống.",
      loading: "Đang tải tiến độ…",
      loadFailed: "Tải tiến độ thất bại",
      empty: "Hoàn thành bài đầu tiên để xem tiến độ của bạn tại đây.",
      skillsTitle: "Kỹ năng",
      skillsSub: "Ước lượng từ các bài đã chấm",
      bandGood: "tốt",
      bandAverage: "trung bình",
      bandPractice: "cần luyện",
      notEnoughData: "Chưa đủ dữ liệu",
      noRatedSkills: "Làm thêm vài bài để hệ thống đánh giá được kỹ năng của bạn.",
      scoreTitle: "Điểm tổng",
      scoreSub: "Thang 100, các bài gần nhất",
      trendsTitle: "Xu hướng theo trục",
      trendsSub: "Mức 0–3 qua các bài gần nhất. Khoảng trống: trục không áp dụng.",
      recurringTitle: "Lỗi lặp lại",
      recurringSub: "Thói quen nên luyện, từ các bài gần đây",
      recurringUnit: "bài",
    },
    workspace: {
      eyebrow: "Phòng luyện",
      title: "Chọn một thử thách",
      sub: "Chọn cấp độ luyện tập để vào môi trường đánh giá. Các bộ bài mới đang được biên soạn.",
      searchPlaceholder: "Tìm bài tập…",
      tags: "Thẻ:",
      trainingLevels: "Cấp độ luyện tập",
      tracks: "3 LỘ TRÌNH",
      exercises: "bài tập",
      browse: "Xem",
      businessProblems: "Bài toán doanh nghiệp",
      comingSoon: "Sắp ra mắt",
      realWorld: "Tình huống thực tế",
      locked: "Đã khoá",
    },
    level: {
      trainingLevels: "Cấp độ luyện tập",
      track: "lộ trình",
      exercisesSuffix: "bài tập",
      progress: "Tiến độ",
      solved: "đã giải",
    },
    exerciseList: {
      searchPlaceholder: "Tìm bài tập…",
      sort: "Sắp xếp",
      title: "Tên bài",
      acceptance: "Tỷ lệ đạt",
      level: "Cấp độ",
      solvedSuffix: "Đã giải",
      noMatch: "Không có bài tập khớp bộ lọc.",
      showing: "Hiển thị",
      of: "trên",
      moreCurated: "bài tập · đang biên soạn thêm",
      statusSolved: "Đã giải",
      statusAttempted: "Đang làm",
      statusTodo: "Chưa bắt đầu",
      statusLocked: "Đã khoá",
      unlockHint: "Mở khoá bằng cách hoàn thành các bài trước",
    },
    solve: {
      exercisesSuffix: "bài tập",
      problem: "Đề bài",
      scoringRubric: "Thang chấm điểm",
      initialHypothesis: "Giả thuyết ban đầu",
      hypothesisPlaceholder: "Mô tả hướng tiếp cận trước khi code…",
      logging: "Đang ghi…",
      logHypothesis: "Ghi giả thuyết",
      submit: "Nộp bài",
      submitting: "Đang nộp…",
      runtimeVersion: "CodeProve runner v1.0 · python 3.12",
      collecting: "Đang thu thập test…",
      found: "tìm thấy",
      pending: "(chờ)",
      runningTests: "Đang chạy test…",
      testRunner: "Trình chạy test",
      runTests: "Chạy test",
      running: "Đang chạy…",
      clear: "Xoá",
      passed: "đạt",
      coverage: "độ phủ",
      cielIntro: "Ciel dẫn dắt tư duy của bạn; không bao giờ viết hộ lời giải.",
      cielThinking: "Ciel đang suy nghĩ…",
      verifyHint: "AI có thể sai — hãy chạy thử và kiểm chứng trước khi dùng.",
      promptSuggestions: "Gợi ý câu hỏi",
      askCiel: "Hỏi Ciel…",
      noActiveAttempt: "Chưa có lượt làm. Vui lòng tải lại trang.",
      pasteDisabled: "Dán (paste) đã bị tắt để đảm bảo bài làm là của chính bạn. Hãy tự gõ lời giải.",
      loadingEditor: "Đang tải mã khởi đầu…",
      rubricLabels: ["Thấu hiểu", "Giả thuyết", "Đặt prompt", "Kiểm chứng", "Kiểm thử", "Gỡ lỗi"],
      promptItems: [
        "Giải thích độ phức tạp thời gian",
        "Tôi đang bỏ sót trường hợp biên nào?",
        "Xem lại giả thuyết của tôi",
        "Gợi ý một test case",
      ],
      explainBack: {
        eyebrow: "Giải thích lại",
        title: "Xác minh mức độ hiểu bài của bạn",
        subtitle: "Trả lời mỗi câu hỏi bằng lời của chính bạn. Phần giải thích được dùng để đánh giá mức độ hiểu bài thực sự.",
        placeholder: "Nhập phần giải thích của bạn tại đây…",
        submit: "Gửi câu trả lời",
        submitting: "Đang gửi…",
        cancel: "Huỷ",
        submitError: "Gửi câu trả lời thất bại. Vui lòng thử lại.",
        close: "Đóng",
      },
      // Cost limits (P3.6). Only the remaining count is shown, never the configured caps.
      quota: {
        cielLeft: "Còn {n} tin nhắn với Ciel",
        cielOut: "Bạn đã dùng hết lượt nhắn với Ciel.",
      },
      debug: {
        stepEyebrow: "Bước 1 · Tìm lỗi",
        title: "Khoanh vùng lỗi trước khi sửa",
        intro: "Bấm vào dòng bạn nghĩ gây ra lỗi (tối đa {max} dòng) và viết một câu giải thích vì sao. Lúc này chưa có gì được chấm: đáp án chỉ hiện trên trang phản hồi sau khi nộp bài.",
        editorLocked: "Trình soạn thảo đang khoá cho đến khi bạn khoanh vùng lỗi hoặc bỏ qua bước này.",
        actionsLocked: "Khoanh vùng lỗi trước khi chạy test hoặc nộp bài.",
        codeAria: "Mã khởi đầu, bấm vào dòng để chọn dòng lỗi",
        selectedTag: "đã chọn",
        selectedCount: "Đã chọn {n}/{max} dòng",
        maxReached: "Tối đa {max} dòng. Bỏ chọn một dòng để chọn dòng khác.",
        reasonLabel: "Vì sao chỗ này sai?",
        reasonPlaceholder: "Viết vào đây",
        hintsTitle: "Gợi ý",
        hintButton: "Gợi ý {step}/2",
        hintCost: "Dùng gợi ý sẽ giảm điểm tìm lỗi.",
        hintLoading: "Đang lấy gợi ý…",
        noHintsLeft: "Đã dùng hết gợi ý",
        hintLabel: "Gợi ý {step}",
        submitLocation: "Chốt vị trí lỗi",
        submittingLocation: "Đang ghi…",
        skip: "Bỏ qua",
        skipTitle: "Bỏ qua bước tìm lỗi?",
        skipBody: "Phần tìm lỗi và giải thích lỗi sẽ bị tính 0 điểm. Bạn vẫn sửa code và nộp bài như bình thường.",
        skipConfirm: "Bỏ qua và sửa code",
        skipCancel: "Quay lại",
        located: "Đã ghi vị trí lỗi. Giờ hãy sửa code; đáp án sẽ hiện trên trang phản hồi sau khi nộp bài.",
        failed: "Không ghi được. Vui lòng thử lại.",
        refused: "Hãy chọn ít nhất một dòng, và chỉ những dòng bạn thật sự nghi ngờ.",
        cielLocked: "Hãy tự tìm dòng lỗi trước. Gợi ý của bài sẽ mở sau bước tìm lỗi.",
        cielHintOnly: "Ciel sẽ chỉ gợi ý cách tìm lỗi cho tới khi bạn chọn đúng dòng lỗi.",
      },
      tests: {
        tab: "Test của bạn",
        tabShort: "Test",
        title: "Test của bạn",
        count: "{n}/{max} test",
        saving: "Đang lưu…",
        saved: "Đã lưu",
        saveFailed: "Chưa lưu được",
        requiredNote: "Bài này chấm cả test bạn viết: cần ít nhất {n} test hợp lệ để đạt điểm tối đa phần kiểm thử.",
        validSoFar: "Đã kiểm tra hợp lệ: {n}/{required}",
        learningTitle: "Chế độ học",
        learningNote: "Ở cấp Fresher, viết test là không bắt buộc, nhưng đây là cách tốt để tự kiểm chứng lời giải. Xem ví dụ dưới đây rồi thử viết test của riêng bạn.",
        exampleTitle: "Ví dụ mẫu (từ một test hiển thị của bài)",
        useExample: "Thêm ví dụ này",
        exampleAdded: "Đã thêm vào danh sách",
        categoriesTitle: "Nhóm test đã có",
        categoriesNote: "Chỉ test hợp lệ mới được tính khi nộp bài.",
        missingHintsTitle: "Gợi ý cho nhóm còn thiếu",
        categoryNames: { happy: "Thông thường", boundary: "Giá trị biên", edge: "Tình huống đặc biệt", error: "Xử lý lỗi" },
        categoryHints: {
          happy: "Một đầu vào điển hình đúng như đề bài mô tả.",
          boundary: "Đầu vào nhỏ nhất hoặc lớn nhất có thể: danh sách rỗng, một phần tử, 0, đúng bằng giới hạn.",
          edge: "Trường hợp dễ làm code sai: số âm, phần tử trùng, chữ hoa/thường, ký tự lạ.",
          error: "Đầu vào không hợp lệ: hàm nên trả về gì (None, -1, danh sách rỗng…)?",
        },
        formatTitle: "Cách viết một test",
        formatInput: "Đầu vào: một biểu thức Python gọi hàm hoặc lớp của bài, với giá trị cụ thể.",
        formatClass: "Với lớp, gói các bước trong một lambda và lấy kết quả cuối:",
        // Neutral names on purpose: no example may match a real exercise (it would be a free valid test).
        formatInputExample: "f([1, 2], 3)",
        formatClassExample: "(lambda o: (o.add(1), o.size())[-1])(MyClass())",
        formatRename: "Thay f / MyClass bằng hàm hoặc lớp của bài bạn đang làm.",
        formatExpected: "Mong đợi: giá trị đúng như Python in ra, ví dụ [0, 1], 'abc', None, True. Khoảng trắng không quan trọng.",
        formatRules: "Không dùng import, open, eval, exec, globals hay tên bắt đầu bằng dấu _. Tối đa {max} ký tự.",
        categoryLabel: "Nhóm",
        inputLabel: "Đầu vào",
        expectedLabel: "Mong đợi",
        whyLabel: "Vì sao test này đáng viết?",
        whyShort: "Vì sao",
        inputPlaceholder: "Viết vào đây",
        expectedPlaceholder: "Viết vào đây",
        whyPlaceholder: "Viết vào đây",
        testNumber: "Test {n}",
        check: "Kiểm tra",
        checking: "Đang kiểm tra…",
        remove: "Xoá test",
        add: "Thêm test",
        maxReached: "Tối đa {max} test.",
        empty: "Chưa có test nào. Bấm “Thêm test” để bắt đầu.",
        needsInput: "Chưa lưu: hãy nhập đầu vào.",
        runOnMine: "Chạy trên code của tôi",
        runningMine: "Đang chạy…",
        runSummary: "Code của bạn pass {passed}/{total} test của bạn.",
        runNothing: "Chưa có test nào để chạy.",
        checkValid: "Hợp lệ: lời giải mẫu cho đúng giá trị này.",
        checkWrong: "Sai giá trị mong đợi: lời giải mẫu không cho ra giá trị này.",
        checkException: "Lỗi khi chạy trên lời giải mẫu",
        checkRefused: "Đầu vào không được phép",
        checkRefusedHelp: "Chỉ gọi hàm hoặc lớp của bài với giá trị cụ thể.",
        mineLabel: "Code của bạn",
        minePass: "Pass",
        mineFail: "Fail",
        actualLabel: "thực tế",
        errors: {
          rate_limited: "Bạn đang chạy hơi nhanh. Đợi khoảng một phút rồi thử lại.",
          submitted: "Bài đã nộp, không thể sửa test nữa.",
          invalid: "Máy chủ từ chối một test: kiểm tra độ dài các ô.",
          no_tab: "Bài này không có tab Tests.",
          failed: "Không kết nối được máy chủ. Vui lòng thử lại.",
        },
      },
    },
    axes: {
      Understanding: "Thấu hiểu",
      Hypothesis: "Giả thuyết",
      Prompting: "Đặt prompt",
      Verification: "Kiểm chứng",
      Testing: "Kiểm thử",
      Debugging: "Gỡ lỗi",
    },
    difficulty: { Easy: "Dễ", Medium: "Trung bình", Hard: "Khó" },
    recentStatus: { PASSED: "ĐẠT", REVIEW: "XEM LẠI" },
    levelInfo: {
      fresher: "Giải quyết vấn đề nền tảng với sự dẫn dắt của AI. Xây thói quen cốt lõi: đọc đề, đặt giả thuyết, prompt.",
      junior: "Logic và gỡ lỗi ở mức trung cấp. Kiểm chứng đầu ra của AI và giải thích lại lập luận của bạn.",
      senior: "Kiến trúc nâng cao và suy luận trường hợp biên. Kiểm chứng và kiểm thử ở mức quan trọng cao.",
    },
    feedback: {
      // "green" used to read "Integrity: Verified", which misleadingly implied the
      // attempt itself was verified as good work. It only means no cheating
      // signals (blocked paste, tab-switch, fullscreen exit...) were detected -
      // an empty, 0-score attempt gets the same badge as a strong honest one.
      integrityGreen: "Toàn vẹn: Không phát hiện gian lận",
      integrityYellow: "Toàn vẹn: Cần xem lại",
      integrityRed: "Toàn vẹn: Bị gắn cờ",
      eyebrow: "Báo cáo đánh giá",
      title: "Tổng kết phản hồi",
      loading: "Đang tải báo cáo…",
      noAttemptTitle: "Chưa chọn lượt làm bài",
      noAttemptDesc: "Trang này cần một mã lượt làm bài hợp lệ. Hãy hoàn thành một thử thách trước.",
      errorTitle: "Không tải được báo cáo",
      unknownError: "Lỗi không xác định.",
      backToDashboard: "Về dashboard",
      nextChallenge: "Thử thách tiếp theo",
      outOf: "TRÊN 100",
      tierLabel: "Hạng thông thạo",
      tierNames: {
        Exceptional: "Xuất sắc",
        Strong: "Vững vàng",
        Developing: "Đang phát triển",
        Emerging: "Khởi đầu",
      },
      ringDesc: "Điểm của bạn phản ánh mức thông thạo AI trên sáu trục tư duy.",
      byAxis: "Kết quả theo trục",
      naLabel: "Không áp dụng",
      naReasons: {
        no_failure: "Không có lần chạy test nào thất bại trong lúc làm bài, nên trục này không được chấm.",
        no_ai_use: "Bạn không dùng Ciel trong lượt này.",
        no_ai_code: "Ciel không đưa code nào để bạn kiểm chứng.",
      },
      timelineHeader: "Dòng thời gian & bằng chứng",
      timelineSteps: {
        hypothesis: "Bước 1 · Giả thuyết",
        implementation: "Bước 2 · Triển khai",
        explain_back: "Bước 3 · Giải thích lại",
      },
      timelineTitles: {
        hypothesis: "Ghi lại cách tiếp cận trước khi code",
        implementation: "Lời giải được chạy với bộ test",
        explain_back: "Kiểm chứng lập luận",
      },
      timelineDesc: {
        hypothesisYes: "Một giả thuyết đã được ghi trước lần sửa code đầu tiên.",
        hypothesisNo: "Không có giả thuyết nào được ghi trước khi code.",
        coverage: "Coverage tốt nhất {pct}%.",
        submitPassed: "Pass {passed}/{total} test khi nộp.",
        noTests: "Chưa chạy test nào.",
        explain: "Phần giải thích đạt {score}/20.",
        explainLevel: "Mức giải thích: {level}.",
      },
      // Engine v2 levels (0-3), labels from the backend contract.
      levelNames: ["Chưa đạt", "Cơ bản", "Khá", "Tốt"],
      submitPulse: "Pass khi nộp",
      levelAria: "{axis}: {level} ({n}/3)",
      overallAxis: "Tổng thể",
      severityNames: { high: "Mức độ cao", medium: "Mức độ vừa", low: "Mức độ thấp" },
      categoryNames: {
        happy: "thông thường",
        boundary: "giá trị biên",
        edge: "tình huống đặc biệt",
        error: "xử lý lỗi",
        uncategorized: "khác",
      },
      findingFields: {
        what_happened: "Chuyện gì đã xảy ra",
        why_it_matters: "Vì sao quan trọng",
        how_to_improve: "Cách cải thiện",
        try_next: "Thử tiếp",
      },
      openExercise: "Mở bài {code}",
      testsTitle: "Kết quả bộ test khi nộp",
      testsSummary: "Pass {passed}/{total} · test ẩn {hidden_passed}/{hidden_total}",
      testsSummaryNoHidden: "Pass {passed}/{total}",
      failedGroups: "nhóm chưa pass: {categories}",
      allPassed: "Tất cả test đều pass, kể cả test ẩn.",
      showMoreFailures: "Xem thêm {n} test chưa pass",
      hiddenTag: "test ẩn",
      visibleTag: "test hiển thị",
      inputLabel: "Đầu vào",
      expectedLabel: "Mong đợi",
      actualLabel: "Thực tế",
      errorLabel: "Lỗi",
      strengthsEyebrow: "Điểm tốt",
      strengthsTitle: "Điểm mạnh",
      noStrengths: "Chưa ghi nhận điểm mạnh nào cho lượt làm này.",
      risksEyebrow: "Cần cải thiện",
      risksTitle: "Điểm cần tập trung",
      noRisks: "Không có rủi ro nào bị gắn cờ cho lượt làm này.",
      notes: {
        strong: "Trục {axis} tốt.",
        improve: "Cần cải thiện trục {axis}.",
        accepted_buggy_ai: "Bạn đã chấp nhận code AI chứa lỗi mà không kiểm tra lại.",
        short_prompts: "Một số prompt quá ngắn nên kém hiệu quả.",
      },
      debugReveal: {
        eyebrow: "Bước tìm lỗi",
        title: "Vị trí lỗi",
        summary: "Bạn đã chỉ ra {hit}/{total} chỗ lỗi.",
        skipped: "Bạn đã bỏ qua bước tìm lỗi.",
        hintsUsed: "Gợi ý đã dùng: {n}/2",
        tags: { hit: "✓ đúng", missed: "lỗi ở đây", extra: "bạn chọn" },
        legend: {
          hit: "Dòng lỗi bạn đã chọn",
          missed: "Dòng lỗi bạn chưa chọn",
          extra: "Dòng bạn chọn nhưng không có lỗi",
        },
        explanationLabel: "Giải thích",
        codeUnavailable: "Không tải được mã khởi đầu. Dòng lỗi: {regions}. Dòng bạn chọn: {selected}.",
        none: "không có",
      },
      studentTests: {
        eyebrow: "Kiểm thử",
        title: "Test của bạn",
        summary: "{valid}/{written} test hợp lệ",
        mutants: "Bắt được {killed}/{total} lỗi cài sẵn",
        mutantsHelp: "Lỗi cài sẵn là những phiên bản code được cố ý cài một lỗi; test tốt sẽ làm chúng thất bại.",
        none: "Bạn chưa viết test nào cho bài này.",
        categoriesTitle: "Nhóm test",
        covered: "đã có",
        notCovered: "còn thiếu",
        validTag: "Hợp lệ",
        invalidTag: "Không hợp lệ",
        reasons: {
          wrong_expected: "Giá trị mong đợi không khớp với lời giải mẫu.",
          exception: "Lỗi khi chạy trên lời giải mẫu",
          refused: "Đầu vào không được phép",
        },
        whyLabel: "Vì sao",
        missedTitle: "Loại lỗi test chưa bắt được",
      },
    },
    privacy: {
      signupAgree: "Tôi đã đọc và đồng ý với",
      signupPolicyLink: "Chính sách quyền riêng tư",
      newTab: "(mở trong thẻ mới)",
      dialog: {
        eyebrow: "Quyền riêng tư",
        title: "Trước khi dùng các tính năng AI",
        intro: "Ciel, kiểm tra giả thuyết, nộp bài và explain-back dùng một nhà cung cấp AI (OpenAI). Tóm tắt những gì xảy ra với dữ liệu của bạn:",
        points: [
          "Đề bài và nội dung bạn viết (câu hỏi, code, giả thuyết, câu trả lời) được gửi tới nhà cung cấp AI để xử lý.",
          "Trước khi gửi, chúng tôi xoá họ tên, email và số điện thoại khỏi nội dung. Tên tài khoản, email và mã người dùng của bạn không được gửi đi.",
          "Nếu bật Cá nhân hoá AI, Ciel nhận thêm một bản tóm tắt ngắn về kỹ năng mạnh/yếu của bạn. Bạn có thể tắt bất cứ lúc nào ở trang Hồ sơ.",
        ],
        policyLink: "Đọc Chính sách quyền riêng tư",
        version: "Phiên bản {version}",
        accept: "Đồng ý",
        accepting: "Đang lưu…",
        later: "Để sau",
        laterHint: "Nếu để sau, các tính năng AI ở trên chưa dùng được. Trình soạn thảo, chạy code và trang Tiến độ vẫn dùng bình thường.",
        outdated: "Chính sách vừa được cập nhật. Vui lòng xem lại rồi đồng ý.",
        failed: "Không lưu được lựa chọn của bạn. Thử lại nhé.",
      },
      profile: {
        nav: "Quyền riêng tư",
        title: "Quyền riêng tư",
        sub: "Sự đồng ý của bạn và cách Ciel dùng dữ liệu kỹ năng.",
        consentTitle: "Chính sách quyền riêng tư",
        consentAccepted: "Bạn đã đồng ý phiên bản {version}.",
        consentMissing: "Bạn chưa đồng ý phiên bản hiện tại ({version}). Các tính năng AI cần sự đồng ý này.",
        consentOpen: "Xem và đồng ý",
        policyLink: "Đọc chính sách",
        aiTitle: "Cá nhân hoá AI",
        aiHelp: "Khi bật, Ciel nhận một bản tóm tắt ngắn về kỹ năng mạnh/yếu của bạn (không có tên, email hay code).",
        loading: "Đang tải cài đặt quyền riêng tư…",
        loadFailed: "Không tải được cài đặt quyền riêng tư.",
        saveFailed: "Không lưu được. Thử lại nhé.",
        retry: "Thử lại",
      },
    },
  },
  en: {
    nav: { dashboard: "Dashboard", progress: "Progress", workspace: "Workspace", analytics: "Analytics", daily: "Bug Hunt", problems: "Problems", leaderboard: "Leaderboard", practice: "Visualizer", community: "Community" },
    dashboard: {
      eyebrow: "System Overview",
      dailyTitle: "Today's Bug Hunt",
      dailyBody: "Ciel planted one subtle bug in today's code. Catch it within 60 seconds for a green tier and keep your streak alive.",
      dailyCta: "Play now",
      recommendedTitle: "Recommended next",
      recommendedPractise: "Practise",
      recommendedDebug: "Debug",
      welcome: "Welcome back",
      loadingSub: "Loading your progress...",
      emptySub: "Start your first challenge to see your progress here.",
      readySub: "Your AI-fluency dashboard shows real aggregate data from your scored attempts.",
      loading: "Loading dashboard…",
      loadFailed: "Failed to load dashboard",
      emptyTitle: "No attempts yet - start a challenge",
      emptyDesc: "Complete a scored exercise to see your fluency metrics here.",
      goWorkspace: "Go to Workspace",
      kpiCompleted: "Completed exercises",
      kpiCompletedDelta: "exercises scored",
      kpiStreak: "Day streak",
      kpiStreakDelta: "days active",
      kpiAvg: "Avg fluency score",
      kpiAvgDelta: "out of 100",
      matrixTitle: "Skill competency matrix",
      matrixSub: "6-axis AI-fluency profile",
      recentTitle: "Recent attempts",
      recentLast: "LAST 6",
      viewAll: "View all activity",
      trendTitle: "Fluency trend",
      trendSub: "Score over last attempts",
      byAxisTitle: "Performance by axis",
      pts: "pts",
    },
    progress: {
      eyebrow: "Learner model",
      title: "Progress",
      sub: "Where you are strong, what to practise, and how each axis is moving.",
      loading: "Loading progress…",
      loadFailed: "Failed to load progress",
      empty: "Finish your first exercise to see your progress here.",
      skillsTitle: "Skills",
      skillsSub: "Estimated from your scored exercises",
      bandGood: "good",
      bandAverage: "average",
      bandPractice: "needs practice",
      notEnoughData: "Not enough data yet",
      noRatedSkills: "Do a few more exercises so your skills can be rated.",
      scoreTitle: "Overall score",
      scoreSub: "Out of 100, recent exercises",
      trendsTitle: "Axis trends",
      trendsSub: "Level 0–3 over recent exercises. Gaps: the axis did not apply.",
      recurringTitle: "Recurring issues",
      recurringSub: "Habits to practise, from your recent reports",
      recurringUnit: "",
    },
    workspace: {
      eyebrow: "Workspace",
      title: "Choose a challenge",
      sub: "Pick a training level to enter the assessment workspace. New exercise sets are being curated.",
      searchPlaceholder: "Search exercises…",
      tags: "Tags:",
      trainingLevels: "Training levels",
      tracks: "3 TRACKS",
      exercises: "exercises",
      browse: "Browse",
      businessProblems: "Business problems",
      comingSoon: "Coming soon",
      realWorld: "Real-world scenarios",
      locked: "Locked",
    },
    level: {
      trainingLevels: "Training levels",
      track: "track",
      exercisesSuffix: "exercises",
      progress: "Progress",
      solved: "solved",
    },
    exerciseList: {
      searchPlaceholder: "Search exercises…",
      sort: "Sort",
      title: "Title",
      acceptance: "Acceptance",
      level: "Level",
      solvedSuffix: "Solved",
      noMatch: "No exercises match your filters.",
      showing: "Showing",
      of: "of",
      moreCurated: "exercises · more sets being curated",
      statusSolved: "Solved",
      statusAttempted: "Attempted",
      statusTodo: "Not started",
      statusLocked: "Locked",
      unlockHint: "Unlock by completing earlier exercises",
    },
    solve: {
      exercisesSuffix: "exercises",
      problem: "Problem",
      scoringRubric: "Scoring rubric",
      initialHypothesis: "Initial hypothesis",
      hypothesisPlaceholder: "Describe your approach before coding…",
      logging: "Logging…",
      logHypothesis: "Log hypothesis",
      submit: "Submit",
      submitting: "Submitting…",
      runtimeVersion: "CodeProve runner v1.0 · python 3.12",
      collecting: "Collecting tests…",
      found: "found",
      pending: "(pending)",
      runningTests: "Running tests…",
      testRunner: "Test runner",
      runTests: "Run tests",
      running: "Running…",
      clear: "Clear",
      passed: "passed",
      coverage: "coverage",
      cielIntro: "Ciel guides your reasoning; it never writes the solution for you.",
      cielThinking: "Ciel is thinking…",
      verifyHint: "AI can be wrong — run and verify it before you use it.",
      promptSuggestions: "Prompt suggestions",
      askCiel: "Ask Ciel…",
      noActiveAttempt: "No active attempt. Please reload the page.",
      pasteDisabled: "Paste is disabled so your work stays genuinely yours. Please type your own solution.",
      loadingEditor: "Loading starter code…",
      rubricLabels: ["Understanding", "Hypothesis", "Prompting", "Verification", "Testing", "Debugging"],
      promptItems: [
        "Explain the time complexity",
        "What edge cases am I missing?",
        "Review my hypothesis",
        "Suggest a test case",
      ],
      explainBack: {
        eyebrow: "Explain-back",
        title: "Verify your understanding",
        subtitle: "Answer each question in your own words. Your explanations are used to assess genuine understanding.",
        placeholder: "Type your explanation here…",
        submit: "Submit answers",
        submitting: "Submitting…",
        cancel: "Cancel",
        submitError: "Failed to submit answers. Please try again.",
        close: "Close",
      },
      quota: {
        cielLeft: "{n} Ciel messages left",
        cielOut: "You have no Ciel messages left.",
      },
      debug: {
        stepEyebrow: "Step 1 · Find the bug",
        title: "Locate the bug before fixing it",
        intro: "Click the line(s) you think cause the bug (up to {max}) and write one sentence on why. Nothing is graded yet: the answer is revealed on the feedback page after you submit.",
        editorLocked: "The editor stays locked until you locate the bug or skip this step.",
        actionsLocked: "Locate the bug before running tests or submitting.",
        codeAria: "Starter code, click a line to mark it as buggy",
        selectedTag: "selected",
        selectedCount: "{n}/{max} lines selected",
        maxReached: "Up to {max} lines. Unselect one to pick another.",
        reasonLabel: "Why is this wrong?",
        reasonPlaceholder: "Write here",
        hintsTitle: "Hints",
        hintButton: "Hint {step}/2",
        hintCost: "Using a hint lowers your bug-finding score.",
        hintLoading: "Getting the hint…",
        noHintsLeft: "No hints left",
        hintLabel: "Hint {step}",
        submitLocation: "Confirm bug location",
        submittingLocation: "Saving…",
        skip: "Skip",
        skipTitle: "Skip finding the bug?",
        skipBody: "Finding and explaining the bug will score 0. You can still fix the code and submit as usual.",
        skipConfirm: "Skip and fix the code",
        skipCancel: "Go back",
        located: "Bug location saved. Now fix the code; the answer is revealed on the feedback page after you submit.",
        failed: "Could not save. Please try again.",
        refused: "Select at least one line, and only the lines you suspect.",
        cielLocked: "Find the buggy line yourself first. The exercise hint unlocks after this step.",
        cielHintOnly: "Until you find the buggy line, Ciel will only give hints on how to find it.",
      },
      tests: {
        tab: "Your tests",
        tabShort: "Tests",
        title: "Your tests",
        count: "{n}/{max} tests",
        saving: "Saving…",
        saved: "Saved",
        saveFailed: "Not saved yet",
        requiredNote: "This exercise scores the tests you write: at least {n} valid tests for full marks on testing.",
        validSoFar: "Checked valid: {n}/{required}",
        learningTitle: "Learning mode",
        learningNote: "At Fresher level tests are optional, but writing them is a good way to check your own solution. Look at the example, then try your own.",
        exampleTitle: "Worked example (from a visible test of this exercise)",
        useExample: "Add this example",
        exampleAdded: "Added to your list",
        categoriesTitle: "Test groups covered",
        categoriesNote: "Only valid tests count at submit.",
        missingHintsTitle: "Ideas for the missing groups",
        categoryNames: { happy: "Typical", boundary: "Boundary", edge: "Edge case", error: "Error handling" },
        categoryHints: {
          happy: "A typical input, exactly as the problem describes it.",
          boundary: "The smallest or largest input: empty list, one element, 0, exactly at the limit.",
          edge: "Cases that trip code up: negatives, duplicates, upper/lower case, odd characters.",
          error: "Invalid input: what should the function return (None, -1, an empty list…)?",
        },
        formatTitle: "How to write a test",
        formatInput: "Input: one Python expression calling the exercise's function or class with concrete values.",
        formatClass: "For a class, wrap the steps in a lambda and keep the last result:",
        formatInputExample: "f([1, 2], 3)",
        formatClassExample: "(lambda o: (o.add(1), o.size())[-1])(MyClass())",
        formatRename: "Replace f / MyClass with the function or class of the exercise you are working on.",
        formatExpected: "Expected: the value exactly as Python prints it, e.g. [0, 1], 'abc', None, True. Spacing does not matter.",
        formatRules: "No import, open, eval, exec, globals or names starting with _. At most {max} characters.",
        categoryLabel: "Group",
        inputLabel: "Input",
        expectedLabel: "Expected",
        whyLabel: "Why is this test worth writing?",
        whyShort: "Why",
        inputPlaceholder: "Write here",
        expectedPlaceholder: "Write here",
        whyPlaceholder: "Write here",
        testNumber: "Test {n}",
        check: "Check",
        checking: "Checking…",
        remove: "Remove test",
        add: "Add test",
        maxReached: "At most {max} tests.",
        empty: "No tests yet. Click “Add test” to start.",
        needsInput: "Not saved: enter an input.",
        runOnMine: "Run on my code",
        runningMine: "Running…",
        runSummary: "Your code passes {passed}/{total} of your tests.",
        runNothing: "No tests to run yet.",
        checkValid: "Valid: the reference solution gives this value.",
        checkWrong: "Wrong expected value: the reference solution does not give this value.",
        checkException: "Error on the reference solution",
        checkRefused: "Input not allowed",
        checkRefusedHelp: "Only call the exercise's function or class with concrete values.",
        mineLabel: "Your code",
        minePass: "Pass",
        mineFail: "Fail",
        actualLabel: "actual",
        errors: {
          rate_limited: "You are going a little fast. Wait about a minute and try again.",
          submitted: "The attempt is submitted; tests can no longer change.",
          invalid: "The server refused a test: check the field lengths.",
          no_tab: "This exercise has no Tests tab.",
          failed: "Could not reach the server. Please try again.",
        },
      },
    },
    axes: {
      Understanding: "Understanding",
      Hypothesis: "Hypothesis",
      Prompting: "Prompting",
      Verification: "Verification",
      Testing: "Testing",
      Debugging: "Debugging",
    },
    difficulty: { Easy: "Easy", Medium: "Medium", Hard: "Hard" },
    recentStatus: { PASSED: "PASSED", REVIEW: "REVIEW" },
    levelInfo: {
      fresher: "Foundational problem-solving with AI guidance. Build core habits: read, hypothesise, prompt.",
      junior: "Intermediate logic and debugging. Verify AI output and explain your reasoning back.",
      senior: "Advanced architecture and edge-case reasoning. High-stakes verification and testing.",
    },
    feedback: {
      integrityGreen: "Integrity: No flags detected",
      integrityYellow: "Integrity: Review",
      integrityRed: "Integrity: Flagged",
      eyebrow: "Assessment report",
      title: "Feedback summary",
      loading: "Loading your report…",
      noAttemptTitle: "No attempt selected",
      noAttemptDesc: "This page requires a valid attempt ID. Complete a challenge first.",
      errorTitle: "Could not load report",
      unknownError: "Unknown error.",
      backToDashboard: "Back to dashboard",
      nextChallenge: "Next challenge",
      outOf: "OUT OF 100",
      tierLabel: "Fluency tier",
      tierNames: {
        Exceptional: "Exceptional",
        Strong: "Strong",
        Developing: "Developing",
        Emerging: "Emerging",
      },
      ringDesc: "Your score reflects AI-fluency across six reasoning axes.",
      byAxis: "Performance by axis",
      naLabel: "Not applicable",
      naReasons: {
        no_failure: "No test run failed while you worked, so this axis was not scored.",
        no_ai_use: "You didn't use Ciel in this attempt.",
        no_ai_code: "Ciel gave you no code to verify.",
      },
      timelineHeader: "Process timeline & evidence",
      timelineSteps: {
        hypothesis: "Step 1 · Hypothesis",
        implementation: "Step 2 · Implementation",
        explain_back: "Step 3 · Explain-back",
      },
      timelineTitles: {
        hypothesis: "Approach logged before coding",
        implementation: "Solution ran against tests",
        explain_back: "Reasoning verified",
      },
      timelineDesc: {
        hypothesisYes: "A hypothesis was recorded before the first code edit.",
        hypothesisNo: "No hypothesis was logged before coding.",
        coverage: "Best coverage {pct}%.",
        submitPassed: "Passed {passed}/{total} tests at submit.",
        noTests: "No tests were run.",
        explain: "Explanation scored {score}/20.",
        explainLevel: "Explanation level: {level}.",
      },
      // Engine v2 levels (0-3), labels from the backend contract.
      levelNames: ["Not yet", "Basic", "Good", "Strong"],
      submitPulse: "Passed at submit",
      levelAria: "{axis}: {level} ({n}/3)",
      overallAxis: "Overall",
      severityNames: { high: "High severity", medium: "Medium severity", low: "Low severity" },
      categoryNames: {
        happy: "typical",
        boundary: "boundary",
        edge: "edge",
        error: "error handling",
        uncategorized: "other",
      },
      findingFields: {
        what_happened: "What happened",
        why_it_matters: "Why it matters",
        how_to_improve: "How to improve",
        try_next: "Try next",
      },
      openExercise: "Open {code}",
      testsTitle: "Submit test results",
      testsSummary: "Passed {passed}/{total} · hidden {hidden_passed}/{hidden_total}",
      testsSummaryNoHidden: "Passed {passed}/{total}",
      failedGroups: "groups not passing: {categories}",
      allPassed: "All tests passed, hidden ones included.",
      showMoreFailures: "Show {n} more failing tests",
      hiddenTag: "hidden test",
      visibleTag: "visible test",
      inputLabel: "Input",
      expectedLabel: "Expected",
      actualLabel: "Actual",
      errorLabel: "Error",
      strengthsEyebrow: "What went well",
      strengthsTitle: "Strengths",
      noStrengths: "No strengths recorded for this attempt.",
      risksEyebrow: "To improve",
      risksTitle: "Focus areas",
      noRisks: "No risk areas flagged for this attempt.",
      notes: {
        strong: "Strong {axisLower}.",
        improve: "Improve your {axisLower}.",
        accepted_buggy_ai: "You accepted AI code containing a bug without checking it.",
        short_prompts: "Some prompts were too short to be effective.",
      },
      debugReveal: {
        eyebrow: "Find the bug",
        title: "Bug location",
        summary: "You pointed at {hit}/{total} bug locations.",
        skipped: "You skipped finding the bug.",
        hintsUsed: "Hints used: {n}/2",
        tags: { hit: "✓ found", missed: "bug here", extra: "your pick" },
        legend: {
          hit: "Bug line you selected",
          missed: "Bug line you did not select",
          extra: "Line you selected that has no bug",
        },
        explanationLabel: "Explanation",
        codeUnavailable: "Could not load the starter code. Bug lines: {regions}. Your lines: {selected}.",
        none: "none",
      },
      studentTests: {
        eyebrow: "Testing",
        title: "Your tests",
        summary: "{valid}/{written} valid tests",
        mutants: "Caught {killed}/{total} planted bugs",
        mutantsHelp: "Planted bugs are versions of the code with one bug put in on purpose; a good test makes them fail.",
        none: "You did not write any tests for this exercise.",
        categoriesTitle: "Test groups",
        covered: "covered",
        notCovered: "missing",
        validTag: "Valid",
        invalidTag: "Invalid",
        reasons: {
          wrong_expected: "The expected value does not match the reference solution.",
          exception: "Error on the reference solution",
          refused: "Input not allowed",
        },
        whyLabel: "Why",
        missedTitle: "Kinds of bugs your tests missed",
      },
    },
    privacy: {
      signupAgree: "I have read and accept the",
      signupPolicyLink: "Privacy Policy",
      newTab: "(opens in a new tab)",
      dialog: {
        eyebrow: "Privacy",
        title: "Before you use the AI features",
        intro: "Ciel, the hypothesis check, submitting and explain-back use an AI provider (OpenAI). In short, this is what happens to your data:",
        points: [
          "The exercise and what you write (questions, code, hypotheses, answers) are sent to the AI provider to be processed.",
          "Before sending, we remove names, emails and phone numbers from the text. Your account name, email and user id are never sent.",
          "With AI personalisation on, Ciel also receives a short summary of your strong and weak skills. You can turn it off at any time on your Profile.",
        ],
        policyLink: "Read the Privacy Policy",
        version: "Version {version}",
        accept: "Accept",
        accepting: "Saving…",
        later: "Later",
        laterHint: "If you choose later, the AI features above stay off. The editor, runs and the Progress page work as usual.",
        outdated: "The policy was just updated. Please review it, then accept.",
        failed: "Could not save your choice. Please try again.",
      },
      profile: {
        nav: "Privacy",
        title: "Privacy",
        sub: "Your consent, and how Ciel uses your skill data.",
        consentTitle: "Privacy Policy",
        consentAccepted: "You accepted version {version}.",
        consentMissing: "You have not accepted the current version ({version}). The AI features need it.",
        consentOpen: "Review and accept",
        policyLink: "Read the policy",
        aiTitle: "AI personalisation",
        aiHelp: "When on, Ciel receives a short summary of your strong and weak skills (no name, email or code).",
        loading: "Loading privacy settings…",
        loadFailed: "Could not load your privacy settings.",
        saveFailed: "Could not save. Please try again.",
        retry: "Try again",
      },
    },
  },
} as const;

export type AppContent = (typeof appContent)["vi"];
