// Bilingual UI strings for the authenticated app surfaces (dashboard, workspace,
// exercise list, solve screen). Kept separate from the large marketing dictionary
// in content.ts. Consume via: const { locale } = useI18n(); const t = appContent[locale];

export const appContent = {
  vi: {
    nav: { dashboard: "Bảng điều khiển", workspace: "Phòng luyện", analytics: "Phân tích" },
    dashboard: {
      eyebrow: "Tổng quan hệ thống",
      welcome: "Chào mừng trở lại",
      loadingSub: "Đang tải tiến trình của bạn...",
      emptySub: "Bắt đầu thử thách đầu tiên để xem tiến trình tại đây.",
      readySub: "Bảng năng lực AI hiển thị dữ liệu tổng hợp thật từ các lần làm đã chấm.",
      loading: "Đang tải bảng điều khiển…",
      loadFailed: "Tải bảng điều khiển thất bại",
      emptyTitle: "Chưa có lần làm nào - bắt đầu một thử thách",
      emptyDesc: "Hoàn thành một bài đã chấm điểm để xem chỉ số năng lực tại đây.",
      goWorkspace: "Tới phòng luyện",
      kpiCompleted: "Bài đã hoàn thành",
      kpiCompletedDelta: "bài đã chấm",
      kpiStreak: "Chuỗi ngày",
      kpiStreakDelta: "ngày hoạt động",
      kpiAvg: "Điểm năng lực TB",
      kpiAvgDelta: "trên thang 100",
      matrixTitle: "Ma trận năng lực",
      matrixSub: "Hồ sơ năng lực AI 6 trục",
      recentTitle: "Lần làm gần đây",
      recentLast: "6 GẦN NHẤT",
      viewAll: "Xem tất cả hoạt động",
      trendTitle: "Xu hướng năng lực",
      trendSub: "Điểm qua các lần làm gần đây",
      byAxisTitle: "Hiệu suất theo trục",
      pts: "điểm",
    },
    workspace: {
      eyebrow: "Phòng luyện",
      title: "Chọn một thử thách",
      sub: "Chọn cấp độ luyện tập để vào môi trường đánh giá. Các bộ bài mới đang được biên soạn.",
      searchPlaceholder: "Tìm bài tập…",
      tags: "Thẻ:",
      trainingLevels: "Cấp độ luyện tập",
      tracks: "3 LỘ TRÌNH",
      exercises: "bài tập",
      browse: "Xem",
      businessProblems: "Bài toán doanh nghiệp",
      comingSoon: "Sắp ra mắt",
      realWorld: "Tình huống thực tế",
      locked: "Đã khoá",
    },
    level: {
      trainingLevels: "Cấp độ luyện tập",
      track: "lộ trình",
      exercisesSuffix: "bài tập",
      progress: "Tiến độ",
      solved: "đã giải",
    },
    exerciseList: {
      searchPlaceholder: "Tìm bài tập…",
      sort: "Sắp xếp",
      title: "Tên bài",
      acceptance: "Tỷ lệ đạt",
      level: "Cấp độ",
      solvedSuffix: "Đã giải",
      noMatch: "Không có bài tập khớp bộ lọc.",
      showing: "Hiển thị",
      of: "trên",
      moreCurated: "bài tập · đang biên soạn thêm",
      statusSolved: "Đã giải",
      statusAttempted: "Đang làm",
      statusTodo: "Chưa bắt đầu",
      statusLocked: "Đã khoá",
      unlockHint: "Mở khoá bằng cách hoàn thành các bài trước",
    },
    solve: {
      exercisesSuffix: "bài tập",
      problem: "Đề bài",
      scoringRubric: "Thang chấm điểm",
      initialHypothesis: "Giả thuyết ban đầu",
      hypothesisPlaceholder: "Mô tả hướng tiếp cận trước khi code…",
      logging: "Đang ghi…",
      logHypothesis: "Ghi giả thuyết",
      submit: "Nộp bài",
      submitting: "Đang nộp…",
      runtimeVersion: "CodeProve runner v1.0 · python 3.12",
      collecting: "Đang thu thập test…",
      found: "tìm thấy",
      pending: "(chờ)",
      runningTests: "Đang chạy test…",
      testRunner: "Trình chạy test",
      runTests: "Chạy test",
      running: "Đang chạy…",
      clear: "Xoá",
      passed: "đạt",
      coverage: "độ phủ",
      cielIntro: "Ciel dẫn dắt tư duy của bạn; không bao giờ viết hộ lời giải.",
      cielThinking: "Ciel đang suy nghĩ…",
      verifyHint: "Hãy kiểm chứng kỹ trước khi tin.",
      promptSuggestions: "Gợi ý câu hỏi",
      askCiel: "Hỏi Ciel…",
      noActiveAttempt: "Chưa có lượt làm. Vui lòng tải lại trang.",
      pasteDisabled: "Dán (paste) đã bị tắt để đảm bảo bài làm là của chính bạn. Hãy tự gõ lời giải.",
      rubricLabels: ["Thấu hiểu", "Giả thuyết", "Đặt prompt", "Kiểm chứng", "Kiểm thử", "Gỡ lỗi"],
      promptItems: [
        "Giải thích độ phức tạp thời gian",
        "Tôi đang bỏ sót trường hợp biên nào?",
        "Xem lại giả thuyết của tôi",
        "Gợi ý một test case",
      ],
    },
    axes: {
      Understanding: "Thấu hiểu",
      Hypothesis: "Giả thuyết",
      Prompting: "Đặt prompt",
      Verification: "Kiểm chứng",
      Testing: "Kiểm thử",
      Debugging: "Gỡ lỗi",
    },
    difficulty: { Easy: "Dễ", Medium: "Trung bình", Hard: "Khó" },
    recentStatus: { PASSED: "ĐẠT", REVIEW: "XEM LẠI" },
    levelInfo: {
      fresher: "Giải quyết vấn đề nền tảng với sự dẫn dắt của AI. Xây thói quen cốt lõi: đọc đề, đặt giả thuyết, prompt.",
      junior: "Logic và gỡ lỗi ở mức trung cấp. Kiểm chứng đầu ra của AI và giải thích lại lập luận của bạn.",
      senior: "Kiến trúc nâng cao và suy luận trường hợp biên. Kiểm chứng và kiểm thử ở mức quan trọng cao.",
    },
  },
  en: {
    nav: { dashboard: "Dashboard", workspace: "Workspace", analytics: "Analytics" },
    dashboard: {
      eyebrow: "System Overview",
      welcome: "Welcome back",
      loadingSub: "Loading your progress...",
      emptySub: "Start your first challenge to see your progress here.",
      readySub: "Your AI-fluency dashboard shows real aggregate data from your scored attempts.",
      loading: "Loading dashboard…",
      loadFailed: "Failed to load dashboard",
      emptyTitle: "No attempts yet - start a challenge",
      emptyDesc: "Complete a scored exercise to see your fluency metrics here.",
      goWorkspace: "Go to Workspace",
      kpiCompleted: "Completed exercises",
      kpiCompletedDelta: "exercises scored",
      kpiStreak: "Day streak",
      kpiStreakDelta: "days active",
      kpiAvg: "Avg fluency score",
      kpiAvgDelta: "out of 100",
      matrixTitle: "Skill competency matrix",
      matrixSub: "6-axis AI-fluency profile",
      recentTitle: "Recent attempts",
      recentLast: "LAST 6",
      viewAll: "View all activity",
      trendTitle: "Fluency trend",
      trendSub: "Score over last attempts",
      byAxisTitle: "Performance by axis",
      pts: "pts",
    },
    workspace: {
      eyebrow: "Workspace",
      title: "Choose a challenge",
      sub: "Pick a training level to enter the assessment workspace. New exercise sets are being curated.",
      searchPlaceholder: "Search exercises…",
      tags: "Tags:",
      trainingLevels: "Training levels",
      tracks: "3 TRACKS",
      exercises: "exercises",
      browse: "Browse",
      businessProblems: "Business problems",
      comingSoon: "Coming soon",
      realWorld: "Real-world scenarios",
      locked: "Locked",
    },
    level: {
      trainingLevels: "Training levels",
      track: "track",
      exercisesSuffix: "exercises",
      progress: "Progress",
      solved: "solved",
    },
    exerciseList: {
      searchPlaceholder: "Search exercises…",
      sort: "Sort",
      title: "Title",
      acceptance: "Acceptance",
      level: "Level",
      solvedSuffix: "Solved",
      noMatch: "No exercises match your filters.",
      showing: "Showing",
      of: "of",
      moreCurated: "exercises · more sets being curated",
      statusSolved: "Solved",
      statusAttempted: "Attempted",
      statusTodo: "Not started",
      statusLocked: "Locked",
      unlockHint: "Unlock by completing earlier exercises",
    },
    solve: {
      exercisesSuffix: "exercises",
      problem: "Problem",
      scoringRubric: "Scoring rubric",
      initialHypothesis: "Initial hypothesis",
      hypothesisPlaceholder: "Describe your approach before coding…",
      logging: "Logging…",
      logHypothesis: "Log hypothesis",
      submit: "Submit",
      submitting: "Submitting…",
      runtimeVersion: "CodeProve runner v1.0 · python 3.12",
      collecting: "Collecting tests…",
      found: "found",
      pending: "(pending)",
      runningTests: "Running tests…",
      testRunner: "Test runner",
      runTests: "Run tests",
      running: "Running…",
      clear: "Clear",
      passed: "passed",
      coverage: "coverage",
      cielIntro: "Ciel guides your reasoning; it never writes the solution for you.",
      cielThinking: "Ciel is thinking…",
      verifyHint: "Verify this carefully before trusting it.",
      promptSuggestions: "Prompt suggestions",
      askCiel: "Ask Ciel…",
      noActiveAttempt: "No active attempt. Please reload the page.",
      pasteDisabled: "Paste is disabled so your work stays genuinely yours. Please type your own solution.",
      rubricLabels: ["Understanding", "Hypothesis", "Prompting", "Verification", "Testing", "Debugging"],
      promptItems: [
        "Explain the time complexity",
        "What edge cases am I missing?",
        "Review my hypothesis",
        "Suggest a test case",
      ],
    },
    axes: {
      Understanding: "Understanding",
      Hypothesis: "Hypothesis",
      Prompting: "Prompting",
      Verification: "Verification",
      Testing: "Testing",
      Debugging: "Debugging",
    },
    difficulty: { Easy: "Easy", Medium: "Medium", Hard: "Hard" },
    recentStatus: { PASSED: "PASSED", REVIEW: "REVIEW" },
    levelInfo: {
      fresher: "Foundational problem-solving with AI guidance. Build core habits: read, hypothesise, prompt.",
      junior: "Intermediate logic and debugging. Verify AI output and explain your reasoning back.",
      senior: "Advanced architecture and edge-case reasoning. High-stakes verification and testing.",
    },
  },
} as const;

export type AppContent = (typeof appContent)["vi"];
